import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/layouts/Navbar";
import { cookies } from "next/headers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import { Toaster } from "sonner";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token");

  const isLoggedIn = Boolean(token);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100 flex flex-col gap-6`}
      >
        <Navbar className="w-screen" isLoggedIn={isLoggedIn} />
        <div className="px-16">
          <Toaster />
          {children}
        </div>
      </body>
    </html>
  );
}
